// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Career struct {
	ID          int    `json:"id"`
	Company     string `json:"company"`
	Position    string `json:"position"`
	JobType     string `json:"job_type"`
	Description string `json:"description"`
}

type DeleteStatus struct {
	Iserror bool    `json:"iserror"`
	Message *string `json:"message,omitempty"`
}

type Mutation struct {
}

type NewCareer struct {
	Company     string `json:"company"`
	Position    string `json:"position"`
	JobType     string `json:"jobType"`
	Description string `json:"description"`
}

type NewProfile struct {
	FullName string  `json:"full_name"`
	Age      string  `json:"age"`
	Gender   string  `json:"gender"`
	Address  *string `json:"address,omitempty"`
}

type NewUser struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type Profile struct {
	ID       int     `json:"id"`
	FullName string  `json:"full_name"`
	Age      string  `json:"age"`
	Gender   string  `json:"gender"`
	Address  *string `json:"address,omitempty"`
	UserID   int     `json:"user_id"`
}

type Query struct {
}

type User struct {
	ID          int    `json:"id"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}
